Repository NoName-ForTeam/photo-fiesta, pull requests merged in 2024-09, with the labels that each got.

#8 PROJ-80
  package.json
  pnpm-lock.yaml
  src/features/auth/api/auth.types.ts
  src/features/auth/api/authApi.ts
  src/features/auth/api/index.ts
  src/features/auth/index.ts
  src/pages/_app.tsx
  src/shared/api/baseApi.ts
  src/shared/api/index.ts
  src/shared/store/index.ts
  src/shared/store/store.ts
Labels: feature

#7 feature/proj-68
  src/features/auth/ui/index.ts
  src/features/auth/ui/sentEmail/index.ts
  src/features/auth/ui/sentEmail/sentEmail.module.scss
  src/features/auth/ui/sentEmail/sentEmail.tsx
  src/pages/index.tsx
  src/shared/styles/_mixins.scss
  src/shared/styles/_variables.scss
Labels: feature

#11 Proj-70
  package.json
  pnpm-lock.yaml
  src/features/auth/ui/signUp/index.ts
  src/features/auth/ui/signUp/signUp.module.scss
  src/features/auth/ui/signUp/signUp.tsx
  src/features/auth/ui/signUp/useSignUpForm.tsx
  src/pages/index.tsx
  src/shared/config/regex-constants.ts
  src/shared/styles/_variables.scss
Labels: feature

#12 Bug/proj 86
  package.json
  src/features/auth/ui/sentEmail/sentEmail.module.scss
  src/features/auth/ui/signUp/signUp.module.scss
  src/pages/index.tsx
  src/shared/styles/_variables.scss
Labels: bug

#10 Feature/proj 69
  package.json
  pnpm-lock.yaml
  src/features/auth/ui/authCard/authCard.module.scss
  src/features/auth/ui/authCard/authCard.tsx
  src/features/auth/ui/authCard/index.ts
  src/features/auth/ui/index.ts
  src/features/auth/ui/sentEmail/sentEmail.tsx
  src/features/auth/ui/signIn/index.ts
  src/features/auth/ui/signIn/signIn.module.scss
  src/features/auth/ui/signIn/signIn.tsx
  src/features/auth/ui/signIn/useSignIn.ts
  src/features/auth/ui/signUp/signUp.tsx
  src/features/auth/ui/signUp/useSignUpForm.tsx
  src/pages/index.tsx
  src/shared/styles/_mixins.scss
  src/shared/styles/_variables.scss
Labels: feature

#14 Feature/Proj 82
  pnpm-lock.yaml
  src/features/auth/ui/confirmEmail/confirmEmail.module.scss
  src/features/auth/ui/createNewPassword/createNewPassword.module.scss
  src/features/auth/ui/createNewPassword/createNewPassword.tsx
  src/features/auth/ui/createNewPassword/index.ts
  src/features/auth/ui/createNewPassword/useCreateNewPassword.ts
  src/features/auth/ui/index.ts
  src/features/auth/ui/sentEmail/sentEmail.module.scss
  src/shared/styles/_mixins.scss
Labels: feature

#15 feature/Proj-83
  src/features/auth/ui/forgotPassword/forgotPassword.module.scss
  src/features/auth/ui/forgotPassword/forgotPassword.tsx
  src/features/auth/ui/forgotPassword/index.ts
  src/features/auth/ui/forgotPassword/useForgotPassword.ts
  src/features/auth/ui/index.ts
  src/shared/styles/_mixins.scss
Labels: feature

#16 Proj 65-Terms of Service and Privacy Policy
  package.json
  src/features/auth/ui/privacy/index.tsx
  src/features/auth/ui/privacy/privacy.module.scss
  src/features/auth/ui/service/index.tsx
  src/features/auth/ui/service/terms.module.scss
  src/pages/auth/privacy/index.tsx
  src/pages/auth/service/index.tsx
Labels: feature

#19 Feature/proj 89
  pnpm-lock.yaml
  src/features/auth/ui/confirmEmail/confirmEmail.tsx
  src/features/auth/ui/privacy/privacy.module.scss
  src/features/auth/ui/service/terms.module.scss
  src/features/auth/ui/signIn/signIn.tsx
  src/features/layout/layout.module.scss
  src/pages/auth/createNewPasswordPage/index.tsx
  src/pages/auth/privacy/index.tsx
  src/pages/auth/privacyPolicyPage/index.tsx
  src/pages/auth/service/index.tsx
  src/pages/auth/termsOfServicePage/index.tsx
  src/pages/index.tsx
  src/shared/config/routes.ts
Labels: bug, refactor, feature

#17 Feature/proj 87+91
  package.json
  src/features/auth/api/auth.types.ts
  src/features/auth/api/authApi.ts
  src/features/auth/ui/authCard/authCard.module.scss
  src/features/auth/ui/authCard/authCard.tsx
  src/features/auth/ui/createNewPassword/useCreateNewPassword.ts
  src/features/auth/ui/forgotPassword/forgotPassword.tsx
  src/features/auth/ui/sentEmail/sentEmail.tsx
  src/features/auth/ui/signIn/signIn.module.scss
  src/features/auth/ui/signIn/signIn.tsx
  src/features/auth/ui/signIn/useSignIn.ts
  src/features/auth/ui/signUp/signUp.module.scss
  src/features/auth/ui/signUp/signUp.tsx
  src/features/auth/ui/signUp/useSignUpForm.tsx
  src/features/layout/layout.module.scss
  src/pages/auth/signInPage/index.tsx
  src/pages/index.tsx
  src/shared/config/index.ts
Labels: refactor, feature

#21 Refactor/Proj 92
  package.json
  pnpm-lock.yaml
  src/features/auth/api/auth.types.ts
  src/features/auth/api/authApi.ts
  src/features/auth/ui/authCard/authCard.module.scss
  src/features/auth/ui/authCard/authCard.tsx
  src/features/auth/ui/createNewPassword/useCreateNewPassword.ts
  src/features/auth/ui/forgotPassword/forgotPassword.tsx
  src/features/auth/ui/sentEmail/sentEmail.tsx
  src/features/auth/ui/signIn/signIn.module.scss
  src/features/auth/ui/signIn/signIn.tsx
  src/features/auth/ui/signIn/useSignIn.ts
  src/features/auth/ui/signUp/signUp.module.scss
  src/features/auth/ui/signUp/signUp.tsx
  src/features/auth/ui/signUp/useSignUpForm.tsx
  src/features/layout/layout.module.scss
  src/pages/auth/signInPage/index.tsx
  src/pages/auth/signUp/index.tsx
  src/pages/index.tsx
  src/shared/api/baseApi.ts
  src/shared/config/index.ts
Labels: refactor

#23 Feature/proj 93
  package.json
  pnpm-lock.yaml
  src/features/auth/api/auth.types.ts
  src/features/auth/api/authApi.ts
  src/features/auth/ui/confirmEmail/confirmEmail.tsx
  src/features/auth/ui/createNewPassword/createNewPassword.tsx
  src/features/auth/ui/createNewPassword/useCreateNewPassword.ts
  src/features/auth/ui/signIn/signIn.tsx
  src/features/auth/ui/signUp/useSignUpForm.tsx
  src/features/layout/layout.tsx
  src/pages/_app.tsx
  src/shared/config/apiURLs.ts
  src/shared/config/index.ts
  src/shared/utils/handleErrorResponse.ts
  src/shared/utils/index.ts
  src/shared/utils/isValidErrorResponse.ts
Labels: refactor, feature

#26 refactor: change button variant for signIn and signUp for google and …
  src/features/auth/api/auth.types.ts
  src/features/auth/ui/authCard/authCard.tsx
  src/features/auth/ui/createNewPassword/useCreateNewPassword.ts
  src/features/auth/ui/signIn/signIn.tsx
  src/features/auth/ui/signIn/useSignIn.ts
  src/features/auth/ui/signUp/signUp.tsx
  src/features/auth/ui/signUp/useSignUpForm.tsx
  src/shared/utils/handleErrorResponse.ts
  src/shared/utils/isValidErrorResponse.ts
Labels: refactor

#27 Feature/proj 108
  src/app/api/baseApi.ts
  src/app/api/index.ts
  src/app/store/index.ts
  src/app/store/store.ts
  src/app/styles/_colors.scss
  src/app/styles/_global.scss
  src/app/styles/_mixins.scss
  src/app/styles/_typography.scss
  src/app/styles/_variables.scss
  src/app/styles/index.scss
  src/features/auth/api/authApi.ts
  src/features/auth/ui/authCard/authCard.module.scss
  src/features/auth/ui/confirmEmail/confirmEmail.module.scss
  src/features/auth/ui/createNewPassword/createNewPassword.module.scss
  src/features/auth/ui/expiredEmail/expiredEmail.module.scss
  src/features/auth/ui/expiredEmail/expiredEmail.tsx
  src/features/auth/ui/forgotPassword/forgotPassword.module.scss
  src/features/auth/ui/privacyPolicy/privacyPolicy.module.scss
  src/features/auth/ui/sentEmail/sentEmail.module.scss
  src/features/auth/ui/signIn/signIn.module.scss
  src/features/auth/ui/signUp/signUp.module.scss
  src/features/auth/ui/termsOfService/termsOfService.module.scss
  src/features/layout/layout.module.scss
  src/pages/_app.tsx
  src/pages/index.tsx
  tsconfig.json
Labels: bug, feature

#28 refactor/proj-113
  src/features/layout/layout.tsx
  src/pages/index.tsx
  src/shared/ui/header/header.module.scss
  src/shared/ui/header/header.tsx
  src/shared/ui/header/index.ts
  src/shared/ui/index.ts
Labels: refactor

#29 fix:fix bug with error messages in useCreateNewPassword
  src/features/auth/api/authApi.ts
  src/features/auth/ui/createNewPassword/useCreateNewPassword.ts
  src/features/auth/ui/forgotPassword/useForgotPassword.ts
  src/features/auth/ui/signIn/useSignIn.ts
  src/features/auth/ui/signUp/useSignUpForm.tsx
  src/shared/ui/index.ts
  src/shared/utils/checkErrorMessages.ts
  src/shared/utils/commonFormUtils.ts
  src/shared/utils/index.ts
Labels: bug, refactor

#30 PROJ-112
  .eslintrc.cjs
  next.config.mjs
  src/features/auth/ui/confirmEmail/confirmEmail.tsx
  src/features/auth/ui/createNewPassword/createNewPassword.tsx
  src/features/auth/ui/expiredEmail/expiredEmail.tsx
  src/features/auth/ui/forgotPassword/forgotPassword.module.scss
  src/features/auth/ui/forgotPassword/forgotPassword.tsx
  src/features/auth/ui/privacyPolicy/privacyPolicy.tsx
  src/features/auth/ui/sentEmail/sentEmail.tsx
  src/features/auth/ui/signIn/signIn.tsx
  src/features/auth/ui/signUp/signUp.tsx
  src/features/auth/ui/termsOfService/termsOfService.tsx
  src/shared/config/locales/en.ts
  src/shared/config/locales/index.ts
  src/shared/config/locales/ru.ts
  src/shared/config/regex-constants.ts
  src/shared/ui/header/header.module.scss
  src/shared/ui/header/header.tsx
  src/shared/ui/index.ts
  src/shared/ui/languageSelect/index.ts
  src/shared/ui/languageSelect/languageSelect.module.scss
  src/shared/ui/languageSelect/languageSelect.tsx
  src/shared/ui/trans/index.ts
  src/shared/ui/trans/trans.tsx
  src/shared/utils/hooks/index.ts
  src/shared/utils/hooks/useTranslation.ts
  src/shared/utils/index.ts
Labels: feature

#31 Feature/proj 100
  README.md
  package.json
  pnpm-lock.yaml
  src/app/api/baseApi.ts
  src/app/api/baseQueryWithReauth.ts
  src/app/store/store.ts
  src/features/auth/api/auth.types.ts
  src/features/auth/api/authApi.ts
  src/features/auth/ui/signIn/signIn.tsx
  src/features/auth/ui/signIn/useSignIn.ts
  src/features/auth/ui/signIn/useSignIn.tsx
  src/features/layout/layout.tsx
  src/features/profile/profile.tsx
  src/pages/_app.tsx
  src/pages/auth/forgotPasswordPage/index.tsx
  src/pages/auth/privacyPolicyPage/index.tsx
  src/pages/auth/recovery/index.tsx
  src/pages/auth/registration-confirmation/index.tsx
  src/pages/auth/signInPage/index.tsx
  src/pages/auth/signUpPage/index.tsx
  src/pages/auth/termsOfServicePage/index.tsx
  src/pages/profile/[userId].tsx
  src/shared/utils/storage.ts
Labels: refactor, feature

#37 fix: fix bugs with recaptcha and button in sentEmail
  .env
  src/features/auth/ui/sentEmail/sentEmail.tsx
  src/features/layout/layout.module.scss
  src/shared/config/locales/en.ts
  src/shared/config/locales/ru.ts
Labels: bug, refactor

#36 PROJ-136
  src/features/auth/ui/privacyPolicy/privacyList.tsx
  src/features/auth/ui/privacyPolicy/privacyPolicy.module.scss
  src/features/auth/ui/privacyPolicy/privacyPolicy.tsx
  src/features/auth/ui/privacyPolicy/usePrivacy.ts
  src/features/auth/ui/termsOfService/termsList.tsx
  src/features/auth/ui/termsOfService/termsOfService.module.scss
  src/features/auth/ui/termsOfService/termsOfService.tsx
  src/features/auth/ui/termsOfService/useTerms.ts
  src/shared/config/locales/en.ts
  src/shared/config/locales/ru.ts
  src/shared/ui/languageSelect/languageSelect.tsx
Labels: refactor

#38 Feature/proj 106
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/api/baseQueryWithReauth.ts
  src/app/styles/_mixins.scss
  src/app/styles/_variables.scss
  src/features/auth/api/auth.types.ts
  src/features/auth/api/authApi.ts
  src/features/auth/ui/authCard/authCard.module.scss
  src/features/auth/ui/expiredEmail/expiredEmail.tsx
  src/features/auth/ui/forgotPassword/useForgotPassword.ts
  src/features/auth/ui/logout/useLogout.tsx
  src/features/auth/ui/sentEmail/sentEmail.module.scss
  src/features/auth/ui/signIn/useSignIn.ts
  src/features/auth/ui/signUp/signUp.module.scss
  src/features/index.ts
  src/features/layout/layout.tsx
  src/features/profile/api/index.ts
  src/features/profile/api/profile.types.ts
  src/features/profile/index.ts
  src/features/profile/profile.tsx
  src/features/profile/ui/index.ts
  src/features/profile/ui/profile/index.ts
  src/features/profile/ui/profile/profile.module.scss
  src/features/profile/ui/profile/profile.tsx
  src/features/profile/ui/settings/generalInfo/generalInfo.module.scss
  src/features/profile/ui/settings/generalInfo/generalInfo.tsx
  src/features/profile/ui/settings/generalInfo/index.ts
  src/features/profile/ui/settings/generalInfo/useGeneralInfo.ts
  src/features/profile/ui/settings/generalInfo/useModalAddPhoto.ts
  src/features/profile/ui/settings/index.ts
  src/pages/404.tsx
  src/pages/home/index.tsx
  src/pages/profile/settings/generalInfoPage/index.tsx
  src/shared/api/index.ts
  src/shared/api/types.ts
  src/shared/config/apiURLs.ts
  src/shared/config/index.ts
  src/shared/config/locationsData.ts
  src/shared/config/photo-constants.ts
  src/shared/config/regex-constants.ts
  src/shared/config/routes.ts
  src/shared/ui/FormDatePicker.tsx
  src/shared/ui/datePicker/datePicker.module.scss
  src/shared/ui/datePicker/datePicker.tsx
  src/shared/ui/datePicker/index.ts
  src/shared/ui/header/header.module.scss
  src/shared/ui/index.ts
  src/shared/ui/sidebar/sidebar.tsx
  src/shared/ui/trans/trans.tsx
  src/shared/utils/checkErrorMessages.ts
  src/shared/utils/commonFormUtils.ts
  src/shared/utils/create-component.mjs
  src/shared/utils/hooks/useTranslation.ts
  src/shared/utils/index.ts
  src/shared/utils/isValidErrorResponse.ts
  src/shared/utils/storage.ts
Labels: refactor, feature

#39 refactor: refactoring after review
  src/features/auth/ui/index.ts
  src/features/auth/ui/logout/index.ts
  src/features/auth/ui/logout/logoutModal/index.ts
  src/features/auth/ui/logout/logoutModal/logoutModal.module.scss
  src/features/auth/ui/logout/logoutModal/logoutModal.tsx
  src/features/auth/ui/logout/useLogout.tsx
  src/shared/ui/sidebar/sidebar.tsx
Labels: refactor

#40 Feature/proj 145
  src/app/api/baseApi.ts
  src/app/api/baseQueryWithReauth.ts
  src/app/styles/_mixins.scss
  src/features/auth/api/authApi.ts
  src/features/index.ts
  src/features/modals/index.ts
  src/features/modals/ui/index.ts
  src/features/modals/ui/modalAddPhoto/index.ts
  src/features/modals/ui/modalAddPhoto/modalAddPhoto.module.scss
  src/features/modals/ui/modalAddPhoto/modalAddPhoto.tsx
  src/features/modals/ui/modalAddPhoto/useModalAddPhoto.ts
  src/features/profile/api/index.ts
  src/features/profile/api/profile.types.ts
  src/features/profile/api/profileApi.ts
  src/features/profile/ui/settings/generalInfo/generalInfo.module.scss
  src/features/profile/ui/settings/generalInfo/generalInfo.tsx
  src/features/profile/ui/settings/generalInfo/useGeneralInfo.ts
  src/shared/config/apiURLs.ts
  src/shared/utils/imageUtils.ts
  src/shared/utils/index.ts
Labels: refactor, feature

#44 refactor: change styles and update sidebar
  src/app/styles/_global.scss
  src/features/profile/ui/settings/accountManagement/accountManagement.module.scss
  src/features/profile/ui/settings/accountManagement/accountManagements.tsx
  src/features/profile/ui/settings/devices/devices.module.scss
  src/features/profile/ui/settings/devices/devices.tsx
  src/features/profile/ui/settings/generalInfo/generalInfo.module.scss
  src/features/profile/ui/settings/myPayments/myPayments.module.scss
  src/features/profile/ui/settings/myPayments/myPayments.tsx
  src/shared/ui/sidebar/sidebar.tsx
  src/shared/ui/sidebar/useSidebar.ts
Labels: bug, refactor

#45 Feature/proj 156
  next.config.mjs
  src/features/layout/layout.module.scss
  src/features/profile/ui/profile/profile.module.scss
  src/features/profile/ui/profile/profile.tsx
  src/features/profile/ui/profile/useProfile.ts
  src/features/profile/ui/settings/generalInfo/generalInfo.tsx
  src/features/profile/ui/settings/generalInfo/useGeneralInfo.ts
  src/features/profile/ui/settings/settings.module.scss
  src/shared/assets/img/index.ts
  src/shared/config/routes.ts
  src/shared/ui/sidebar/sidebar.module.scss
  src/shared/ui/sidebar/sidebar.tsx
Labels: refactor, feature

#46 Feature/proj 157
  src/features/auth/api/auth.types.ts
  src/features/auth/api/authApi.ts
  src/features/auth/ui/index.ts
  src/features/auth/ui/logout/index.ts
  src/features/auth/ui/logout/logoutModal/index.ts
  src/features/index.ts
  src/features/modals/ui/modalAddPhoto/index.ts
  src/features/profile/api/profileApi.ts
  src/features/profile/ui/profile/profile.tsx
  src/features/profile/ui/settings/generalInfo/generalInfo.module.scss
  src/features/profile/ui/settings/generalInfo/generalInfo.tsx
  src/features/profile/ui/settings/generalInfo/hooks/index.ts
  src/features/profile/ui/settings/generalInfo/hooks/useGeneralInfo.ts
  src/features/profile/ui/settings/generalInfo/hooks/usePhotoPreview.ts
  src/features/profile/ui/settings/settings.tsx
  src/pages/_app.tsx
  src/shared/config/apiURLs.ts
  src/shared/ui/index.ts
  src/shared/ui/profileStat/profileStat.tsx
  src/shared/utils/hooks/index.ts
  src/shared/utils/hooks/useLogout.tsx
  src/widgets/header/header.module.scss
  src/widgets/header/header.tsx
  src/widgets/header/index.ts
  src/widgets/index.ts
  src/widgets/layout/index.ts
  src/widgets/layout/layout.module.scss
  src/widgets/layout/layout.tsx
  src/widgets/modals/index.ts
  src/widgets/modals/ui/confirmationModal/confirmationModal.module.scss
  src/widgets/modals/ui/confirmationModal/confirmationModal.tsx
  src/widgets/modals/ui/confirmationModal/index.ts
  src/widgets/modals/ui/index.ts
  src/widgets/modals/ui/modalAddPhoto/index.ts
  src/widgets/modals/ui/modalAddPhoto/modalAddPhoto.module.scss
  src/widgets/modals/ui/modalAddPhoto/modalAddPhoto.tsx
  src/widgets/modals/ui/modalAddPhoto/useModalAddPhoto.ts
  src/widgets/sidebar/index.ts
  src/widgets/sidebar/sidebar.module.scss
  src/widgets/sidebar/sidebar.tsx
  src/widgets/sidebar/useSidebar.ts
Labels: refactor, feature

#47 Refactor/proj 158
  README.md
  contributing.md
  src/app/api/baseApi.ts
  src/app/api/baseQueryWithReauth.ts
  src/features/auth/api/authApi.ts
  src/features/index.ts
  src/features/posts/index.ts
  src/features/posts/ui/index.ts
  src/features/posts/ui/post/post.tsx
  src/features/posts/ui/postList/PostList.tsx
  src/features/posts/ui/postList/index.ts
  src/pages/_app.tsx
  src/pages/profile/[userId].tsx
  src/shared/assets/img/screen_photo-fiesta.png
  src/widgets/sidebar/sidebar.tsx
  src/widgets/sidebar/useSidebar.ts
Labels: bug, refactor
