Repository NoName-ForTeam/photo-fiesta, pull requests merged in 2024-10, with the labels that each got.

#50 Bug/proj 160
  public/favicon.jpg
  src/app/api/baseQueryWithReauth.ts
  src/features/auth/api/authApi.ts
  src/features/auth/ui/signIn/useSignIn.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/profile/[userId].tsx
  src/widgets/layout/layout.tsx
  src/widgets/sidebar/useSidebar.ts
Labels: bug, refactor, feature

#51 refactor: add profileInfo from server
  src/features/profile/ui/profile/profile.tsx
  src/features/profile/ui/profile/useProfile.ts
  src/shared/ui/index.ts
  src/shared/ui/profileAvatar/index.ts
  src/shared/ui/profileAvatar/profileAvatar.module.scss
  src/shared/ui/profileAvatar/profileAvatar.tsx
Labels: feature

#54 Feature/proj 161
  src/app/api/baseApi.ts
  src/features/profile/api/index.ts
  src/features/profile/api/profile/index.ts
  src/features/profile/api/profile/profile.types.ts
  src/features/profile/api/profile/profileApi.ts
  src/features/profile/api/subscriptions/index.ts
  src/features/profile/api/subscriptions/subscriptions.types.ts
  src/features/profile/api/subscriptions/subscriptionsApi.ts
  src/shared/config/apiURLs.ts
Labels: feature

#55 Feature/proj 162
  src/features/profile/ui/settings/accountManagement/accountManagement.module.scss
  src/features/profile/ui/settings/accountManagement/accountManagements.tsx
  src/features/profile/ui/settings/devices/devices.module.scss
  src/features/profile/ui/settings/generalInfo/generalInfo.module.scss
  src/features/profile/ui/settings/myPayments/myPayments.module.scss
  src/pages/index.tsx
  src/pages/profile/[userId].tsx
  src/shared/assets/icons/components/PaypalSvgrepoCom4.tsx
  src/shared/assets/icons/components/StripeSvgrepoCom4.tsx
  src/widgets/modals/ui/confirmationModal/confirmationModal.module.scss
  src/widgets/modals/ui/confirmationModal/confirmationModal.tsx
Labels: refactor, feature

#56 Feature/proj 103
  src/app/api/baseApi.ts
  src/features/posts/api/index.ts
  src/features/posts/api/posts.types.ts
  src/features/posts/api/postsApi.ts
  src/features/posts/index.ts
  src/features/posts/ui/imagePostModal/imagePostModal.module.scss
  src/features/posts/ui/imagePostModal/imagePostModal.tsx
  src/features/posts/ui/imagePostModal/index.ts
  src/features/posts/ui/imagePostModal/useImagePostModal.tsx
  src/features/posts/ui/index.ts
  src/features/posts/ui/post/index.ts
  src/features/posts/ui/post/post.module.scss
  src/features/posts/ui/post/post.tsx
  src/features/posts/ui/postList/index.ts
  src/features/posts/ui/postList/postList.module.scss
  src/features/posts/ui/postList/postList.tsx
  src/features/profile/api/profile/profileApi.ts
  src/features/profile/ui/profile/index.ts
  src/features/profile/ui/profile/profile.tsx
  src/features/profile/ui/settings/generalInfo/generalInfo.tsx
  src/shared/config/apiURLs.ts
  src/shared/utils/hooks/useLogout.tsx
  src/widgets/sidebar/sidebar.tsx
Labels: feature

#57 feature: add useAccountManagement hook
  .env
  src/features/profile/ui/settings/accountManagement/accountManagement.module.scss
  src/features/profile/ui/settings/accountManagement/accountManagements.tsx
  src/features/profile/ui/settings/accountManagement/useAccountManagement.ts
  src/shared/config/constants.ts
  src/shared/config/index.ts
  src/shared/utils/checkErrorMessages.ts
  src/shared/utils/hooks/index.ts
  src/shared/utils/hooks/useDelayedLoading.ts
Labels: refactor, feature

#58 Proj-151
  src/features/index.ts
  src/features/public/api/index.ts
  src/features/public/api/public.types.ts
  src/features/public/api/publicApi.ts
  src/features/public/index.ts
  src/features/public/ui/index.ts
  src/features/public/ui/public.tsx
  src/features/public/ui/publicPage.module.scss
  src/pages/index.tsx
  src/pages/public/index.tsx
  src/shared/config/apiURLs.ts
  src/shared/config/routes.ts
  src/shared/ui/index.ts
  src/shared/ui/registeredUsersCounter/index.ts
  src/shared/ui/registeredUsersCounter/ui/index.ts
  src/shared/ui/registeredUsersCounter/ui/registeredUsersCounter.module.scss
  src/shared/ui/registeredUsersCounter/ui/registeredUsersCounter.tsx
Labels: feature

#60 Refactoring create post
  src/features/posts/ui/imagePostModal/imagePostModal.module.scss
  src/features/posts/ui/imagePostModal/imagePostModal.tsx
  src/features/posts/ui/imagePostModal/useImagePostModal.tsx
  src/features/posts/ui/post/index.ts
  src/features/posts/ui/post/post.module.scss
  src/features/posts/ui/post/post.tsx
  src/features/posts/ui/post/postForm/index.ts
  src/features/posts/ui/post/postForm/postForm.module.scss
  src/features/posts/ui/post/postForm/postForm.tsx
  src/features/posts/ui/post/postForm/usePostForm.ts
  src/features/posts/ui/post/usePost.ts
  src/features/posts/ui/postList/postList.tsx
  src/shared/utils/commonFormUtils.ts
  src/widgets/modals/ui/confirmationModal/confirmationModal.module.scss
  src/widgets/modals/ui/confirmationModal/confirmationModal.tsx
  src/widgets/sidebar/sidebar.tsx
Labels: refactor

#64 Posts refactoring
  package.json
  pnpm-lock.yaml
  src/features/posts/api/postsApi.ts
  src/features/posts/ui/imagePostModal/CreatePostModal.tsx
  src/features/posts/ui/imagePostModal/imagePostModal.tsx
  src/features/posts/ui/imagePostModal/index.ts
  src/features/posts/ui/imagePostModal/useImagePostModal.tsx
  src/features/posts/ui/post/post.tsx
  src/features/posts/ui/post/postForm/postForm.tsx
  src/features/posts/ui/post/postForm/usePostForm.ts
  src/shared/config/apiURLs.ts
  src/shared/utils/hooks/useChangeTitle.ts
  src/widgets/modals/ui/modalAddPhoto/modalAddPhoto.tsx
  src/widgets/modals/ui/modalAddPhoto/useModalAddPhoto.ts
  src/widgets/sidebar/sidebar.tsx
  src/widgets/sidebar/useSidebar.ts
Labels: refactor

#63 Refactor/proj 171
  src/app/styles/_mixins.scss
  src/features/profile/ui/profile/profile.module.scss
  src/features/profile/ui/settings/accountManagement/accountManagement.module.scss
  src/features/profile/ui/settings/accountManagement/accountManagements.tsx
  src/features/profile/ui/settings/accountManagement/accountTypes/accountTypes.module.scss
  src/features/profile/ui/settings/accountManagement/accountTypes/accountTypes.tsx
  src/features/profile/ui/settings/accountManagement/accountTypes/index.ts
  src/features/profile/ui/settings/accountManagement/currentSubscription/currentSubscription.module.scss
  src/features/profile/ui/settings/accountManagement/currentSubscription/currentSubscription.tsx
  src/features/profile/ui/settings/accountManagement/currentSubscription/index.ts
  src/features/profile/ui/settings/accountManagement/paymentMethodSelector/index.ts
  src/features/profile/ui/settings/accountManagement/paymentMethodSelector/paymentMethodSelector.module.scss
  src/features/profile/ui/settings/accountManagement/paymentMethodSelector/paymentMethodSelector.tsx
  src/features/profile/ui/settings/accountManagement/radioBlock/index.ts
  src/features/profile/ui/settings/accountManagement/radioBlock/radioBlock.module.scss
  src/features/profile/ui/settings/accountManagement/radioBlock/radioBlock.tsx
  src/features/profile/ui/settings/accountManagement/subscriptionCosts/index.ts
  src/features/profile/ui/settings/accountManagement/subscriptionCosts/subscriptionCosts.module.scss
  src/features/profile/ui/settings/accountManagement/subscriptionCosts/subscriptionCosts.tsx
  src/features/profile/ui/settings/accountManagement/useAccountManagement.ts
  src/features/profile/ui/settings/myPayments/myPayments.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/profile/[userId].tsx
  src/widgets/layout/layout.tsx
  src/widgets/sidebar/sidebar.tsx
  src/widgets/sidebar/useSidebar.ts
Labels: refactor

#65 chore: change deployment.yml
  src/widgets/layout/layout.tsx
Labels: refactor

#66 Fix/proj 177
  src/pages/index.tsx
  src/shared/utils/storage.ts
  src/widgets/layout/layout.tsx
  src/widgets/sidebar/useSidebar.ts
Labels: bug, refactor

#70 chore: update package.json: up ui-lib version to 0.0.12
  package.json
Labels: documentation

#71 commit: update ui-lib to version 0.0.13
  package.json
  pnpm-lock.yaml
  src/pages/_app.tsx
Labels: documentation

#72 Refactor/proj 181
  package.json
  pnpm-lock.yaml
  src/features/profile/api/subscriptions/subscriptions.types.ts
  src/features/profile/api/subscriptions/subscriptionsApi.ts
  src/features/profile/ui/settings/accountManagement/accountManagements.tsx
  src/features/profile/ui/settings/accountManagement/accountTypes/accountTypes.tsx
  src/features/profile/ui/settings/accountManagement/currentSubscription/currentSubscription.tsx
  src/features/profile/ui/settings/accountManagement/paymentMethodSelector/paymentMethodSelector.tsx
  src/features/profile/ui/settings/accountManagement/subscriptionCosts/subscriptionCosts.tsx
  src/shared/config/apiURLs.ts
  src/shared/ui/index.ts
  src/shared/ui/popover/index.ts
  src/shared/ui/popover/popover.module.scss
  src/shared/ui/popover/popover.tsx
  src/shared/utils/hooks/useModal.ts
Labels: refactor

#69 PROJ-174
  src/app/api/baseApi.ts
  src/app/styles/_mixins.scss
  src/features/auth/api/authApi.ts
  src/features/device/api/device.api.ts
  src/features/device/api/device.types.ts
  src/features/device/api/index.ts
  src/features/device/index.ts
  src/features/device/ui/device.module.scss
  src/features/device/ui/deviceComp.tsx
  src/features/device/ui/index.ts
  src/features/profile/ui/settings/devices/devices.module.scss
  src/features/profile/ui/settings/devices/devices.tsx
  src/shared/assets/icons/components/Chrome.tsx
  src/shared/assets/icons/components/PC.tsx
  src/shared/assets/icons/components/Phone.tsx
  src/shared/assets/icons/components/index.ts
  src/shared/config/locales/en.ts
  src/shared/config/locales/ru.ts
  src/shared/utils/formatDate.ts
  src/shared/utils/index.ts
Labels: feature

#73 Proj 182
  src/features/posts/ui/imagePostModal/imagePostModal.module.scss
  src/features/posts/ui/imagePostModal/imagePostModal.tsx
  src/shared/ui/popover/popover.tsx
Labels: feature

#74 create API & types for notifications
  src/app/api/baseApi.ts
  src/features/profile/api/index.ts
  src/features/profile/api/notifications/index.ts
  src/features/profile/api/notifications/notifications.types.ts
  src/features/profile/api/notifications/notificationsApi.ts
  src/shared/config/apiURLs.ts
Labels: feature

#75 feature/PROJ-186.1: add MobilePopover component
  src/shared/config/locales/en.ts
  src/shared/config/locales/ru.ts
  src/widgets/header/header.module.scss
  src/widgets/header/header.tsx
  src/widgets/index.ts
  src/widgets/mobilePopover/index.ts
  src/widgets/mobilePopover/mobilePopover.module.scss
  src/widgets/mobilePopover/mobilePopover.tsx
  src/widgets/sidebar/sidebar.tsx
Labels: feature

#78 fix: update styles for settings.module.scss: add with for child div o…
  src/features/profile/ui/settings/settings.module.scss
Labels: bug
