Repository NoName-ForTeam/photo-fiesta, pull requests merged in 2024-11, with the labels that each got.

#79 Feature/proj 153
  src/app/styles/_mixins.scss
  src/app/styles/_variables.scss
  src/features/posts/ui/imagePostModal/imagePostModal.module.scss
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/home/index.tsx
  src/pages/profile/[userId].tsx
  src/pages/public/index.tsx
  src/shared/config/constants.ts
  src/shared/ui/preloader/preloader.module.scss
  src/widgets/errorMessage/errorMessage.module.scss
  src/widgets/errorMessage/errorMessage.tsx
  src/widgets/errorMessage/index.ts
  src/widgets/index.ts
  src/widgets/layout/layout.tsx
  src/widgets/modals/ui/confirmationModal/confirmationModal.module.scss
  src/widgets/modals/ui/modalAddPhoto/modalAddPhoto.module.scss
  src/widgets/modals/ui/modalAddPhoto/modalAddPhoto.tsx
  src/widgets/modals/ui/modalAddPhoto/useModalAddPhoto.ts
  src/widgets/slider/slider.module.scss
  src/widgets/slider/slider.tsx
Labels: refactor

#80 feature/PROJ-197.1: implement mobile Profile
  src/features/posts/ui/postList/postList.module.scss
  src/features/posts/ui/postList/postList.tsx
  src/features/profile/ui/profile/profile.module.scss
  src/features/profile/ui/profile/profile.tsx
  src/shared/config/regex-constants.ts
  src/shared/ui/profileStat/profileStat.module.scss
  src/shared/ui/profileStat/profileStat.tsx
  src/widgets/header/header.module.scss
  src/widgets/layout/layout.module.scss
Labels: feature

#76 refactor: dekstop and mobile styles
  src/features/auth/ui/privacyPolicy/privacyList.tsx
  src/features/auth/ui/privacyPolicy/privacyPolicy.module.scss
  src/features/auth/ui/privacyPolicy/privacyPolicy.tsx
  src/features/auth/ui/termsOfService/termsList.tsx
  src/features/auth/ui/termsOfService/termsOfService.module.scss
  src/features/auth/ui/termsOfService/termsOfService.tsx
Labels: refactor

#82 feature/PROJ-197.2: implement mobile Settings component (Profile Settings / General Information)
  src/app/styles/_variables.scss
  src/features/profile/ui/settings/generalInfo/generalInfo.module.scss
  src/features/profile/ui/settings/settings.module.scss
  src/features/profile/ui/settings/settings.tsx
  src/widgets/mobileMenu/mobileMenu.module.scss
  src/widgets/mobileMenu/mobileMenu.tsx
  src/widgets/mobilePopover/mobilePopover.module.scss
  src/widgets/mobilePopover/mobilePopover.tsx
Labels: feature

#81 Feature/proj 194
  package.json
  pnpm-lock.yaml
  src/app/api/index.ts
  src/app/api/socketApi.ts
  src/app/styles/_typography.scss
  src/features/notifications/api/index.ts
  src/features/notifications/api/notifications.types.ts
  src/features/notifications/api/notificationsApi.ts
  src/features/notifications/index.ts
  src/features/notifications/ui/index.ts
  src/features/notifications/ui/notification/index.ts
  src/features/notifications/ui/notification/notification.module.scss
  src/features/notifications/ui/notification/notification.tsx
  src/features/notifications/ui/notifications.module.scss
  src/features/notifications/ui/notifications.tsx
  src/features/notifications/ui/notificationsIcon/index.ts
  src/features/notifications/ui/notificationsIcon/notificationsIcon.module.scss
  src/features/notifications/ui/notificationsIcon/notificationsIcon.tsx
  src/features/profile/api/devices/device.api.ts
  src/features/profile/api/devices/device.types.ts
  src/features/profile/api/devices/index.ts
  src/features/profile/api/index.ts
  src/features/profile/ui/settings/devices/deviceComp/device.module.scss
  src/features/profile/ui/settings/devices/deviceComp/deviceComp.tsx
  src/features/profile/ui/settings/devices/deviceComp/index.ts
  src/features/profile/ui/settings/devices/devices.tsx
  src/features/profile/ui/settings/devices/index.ts
  src/shared/config/apiURLs.ts
  src/shared/config/locales/en.ts
  src/shared/config/locales/ru.ts
  src/shared/utils/hooks/index.ts
  src/shared/utils/hooks/useConnectSocket.ts
  src/shared/utils/hooks/useTimeAgo.ts
  src/widgets/header/header.module.scss
  src/widgets/header/header.tsx
Labels: feature

#84 bug/PROJ-216: fix Profile Settings on desktop view
  src/features/profile/ui/settings/settings.module.scss
Labels: bug

#85 chore: up lib version to 0.0.14
  package.json
  pnpm-lock.yaml
Labels: documentation

#83 refactor: styles auth components
  .env
  src/app/styles/_mixins.scss
  src/features/auth/ui/authCard/authCard.module.scss
  src/features/auth/ui/authCard/authCard.tsx
  src/features/auth/ui/createNewPassword/createNewPassword.module.scss
  src/features/auth/ui/createNewPassword/createNewPassword.tsx
  src/features/auth/ui/forgotPassword/forgotPassword.module.scss
  src/features/auth/ui/forgotPassword/forgotPassword.tsx
  src/features/auth/ui/signIn/signIn.module.scss
  src/features/auth/ui/signIn/signIn.tsx
  src/features/auth/ui/signUp/signUp.module.scss
  src/features/auth/ui/signUp/signUp.tsx
Labels: refactor

#87 feature/PROJ-197.3
  src/features/auth/ui/forgotPassword/forgotPassword.module.scss
  src/features/auth/ui/signUp/signUp.module.scss
  src/features/notifications/ui/notificationsIcon/notificationsIcon.module.scss
  src/features/profile/ui/settings/devices/deviceComp/device.module.scss
  src/features/profile/ui/settings/devices/devices.module.scss
  src/widgets/header/header.module.scss
  src/widgets/header/header.tsx
Labels: feature

#89 refactoring postsApi & public Api
  src/app/api/baseApi.ts
  src/features/posts/api/posts.types.ts
  src/features/posts/api/postsApi.ts
  src/features/posts/ui/postList/postList.tsx
  src/features/public/api/public.types.ts
  src/features/public/api/publicApi.ts
  src/shared/config/apiURLs.ts
  src/shared/ui/registeredUsersCounter/ui/registeredUsersCounter.tsx
Labels: refactor

#91 Feature/proj 228
  src/pages/_app.tsx
  src/shared/ui/index.ts
  src/shared/ui/slider/index.ts
  src/shared/ui/slider/slider.module.scss
  src/shared/ui/slider/slider.tsx
  src/widgets/carousel/carousel.module.scss
  src/widgets/carousel/carousel.tsx
  src/widgets/carousel/index.ts
  src/widgets/index.ts
  src/widgets/modals/ui/confirmationModal/confirmationModal.module.scss
Labels: refactor, feature

#90 Feature/proj 189
  package.json
  pnpm-lock.yaml
  src/features/posts/ui/postList/postList.module.scss
  src/features/posts/ui/postList/postList.tsx
  src/features/profile/ui/profile/profile.tsx
  src/features/public/api/public.types.ts
  src/features/public/api/publicApi.ts
  src/features/public/ui/index.ts
  src/features/public/ui/public.tsx
  src/features/public/ui/publicPost/index.ts
  src/features/public/ui/publicPost/publicPost.module.scss
  src/features/public/ui/publicPost/publicPost.tsx
  src/features/public/ui/publicPosts/index.ts
  src/features/public/ui/publicPosts/publicPosts.module.scss
  src/features/public/ui/publicPosts/publicPosts.tsx
  src/features/public/ui/registeredUsersCounter/index.ts
  src/features/public/ui/registeredUsersCounter/registeredUsersCounter.module.scss
  src/features/public/ui/registeredUsersCounter/registeredUsersCounter.tsx
  src/pages/index.tsx
  src/pages/profile/[userId].tsx
  src/pages/public/index.tsx
  src/shared/config/apiURLs.ts
  src/shared/config/routes.ts
  src/shared/ui/index.ts
  src/shared/ui/profileStat/profileStat.tsx
  src/shared/ui/registeredUsersCounter/index.ts
  src/widgets/header/header.tsx
Labels: feature

#92 feature/PROJ-198: implement mobile Settings component (Profile Settings / Account Management, Profile Settings / My payments)
  src/features/profile/ui/settings/accountManagement/accountManagement.module.scss
  src/features/profile/ui/settings/accountManagement/paymentMethodSelector/paymentMethodSelector.module.scss
  src/features/profile/ui/settings/myPayments/myPayments.module.scss
  src/features/profile/ui/settings/myPayments/myPayments.tsx
  src/features/profile/ui/settings/myPayments/myPaymentsCardsMobile/index.ts
  src/features/profile/ui/settings/myPayments/myPaymentsCardsMobile/myPaymentsCardsMobile.module.scss
  src/features/profile/ui/settings/myPayments/myPaymentsCardsMobile/myPaymentsCardsMobile.tsx
  src/features/profile/ui/settings/myPayments/myPaymentsCardsMobile/paymentCard/index.ts
  src/features/profile/ui/settings/myPayments/myPaymentsCardsMobile/paymentCard/paymentCard.module.scss
  src/features/profile/ui/settings/myPayments/myPaymentsCardsMobile/paymentCard/paymentCard.tsx
  src/features/profile/ui/settings/myPayments/myPaymentsList/myPaymentsList.module.scss
  src/features/profile/ui/settings/myPayments/myPaymentsList/myPaymentsList.tsx
Labels: feature

#93 modife profile component for using in variant for unauth user
  src/features/posts/ui/imagePostModal/imagePostModal.tsx
  src/features/posts/ui/postList/postList.tsx
  src/features/public/ui/publicPosts/publicPosts.module.scss
  src/pages/index.tsx
  src/pages/profile/[userId].tsx
  src/shared/utils/hooks/useModal.ts
Labels: refactor

#94 Refactor/proj 229
  package.json
  pnpm-lock.yaml
  src/app/styles/_mixins.scss
  src/features/posts/ui/imagePostModal/CreatePostModal.tsx
  src/features/posts/ui/imagePostModal/imagePostModal.tsx
  src/features/posts/ui/post/post.tsx
  src/features/posts/ui/post/postForm/postForm.tsx
  src/features/posts/ui/post/postForm/usePostForm.ts
  src/features/profile/ui/settings/accountManagement/accountManagements.tsx
  src/features/profile/ui/settings/generalInfo/generalInfo.tsx
  src/pages/_app.tsx
  src/shared/ui/index.ts
  src/shared/ui/profileAvatar/profileAvatar.tsx
  src/shared/ui/rangeSlider/index.ts
  src/shared/ui/rangeSlider/rangeSlider.module.scss
  src/shared/ui/rangeSlider/rangeSlider.tsx
  src/shared/ui/slider/slider.tsx
  src/widgets/carousel/carousel.module.scss
  src/widgets/carousel/carousel.tsx
  src/widgets/carousel/carouselArrows/carouselArrows.module.scss
  src/widgets/carousel/carouselArrows/carouselArrows.types.ts
  src/widgets/carousel/carouselArrows/index.ts
  src/widgets/carousel/carouselArrows/nextArrow.tsx
  src/widgets/carousel/carouselArrows/prevArrow.tsx
  src/widgets/carousel/imageControlButtons/expandPhotoButton/expandPhotoButton.module.scss
  src/widgets/carousel/imageControlButtons/expandPhotoButton/expandPhotoButton.tsx
  src/widgets/carousel/imageControlButtons/expandPhotoButton/index.ts
  src/widgets/carousel/imageControlButtons/imageControlButtons .tsx
  src/widgets/carousel/imageControlButtons/imageControlButtons.module.scss
  src/widgets/carousel/imageControlButtons/index.ts
  src/widgets/carousel/imageControlButtons/zoomPhotoButton/index.ts
  src/widgets/carousel/imageControlButtons/zoomPhotoButton/zoomPhotoButton.module.scss
  src/widgets/carousel/imageControlButtons/zoomPhotoButton/zoomPhotoButton.tsx
  src/widgets/mobileMenu/mobileMenu.tsx
  src/widgets/mobilePopover/mobilePopover.tsx
  src/widgets/modals/ui/confirmationModal/confirmationModal.tsx
  src/widgets/modals/ui/modalAddPhoto/modalAddPhoto.tsx
  src/widgets/modals/ui/modalAddPhoto/useModalAddPhoto.ts
  src/widgets/sidebar/sidebar.tsx
  src/widgets/sidebar/useSidebar.ts
Labels: refactor, feature

#95 fix: fix bug with unique keys in sidebar and mobileMenu components fo…
  src/widgets/mobileMenu/mobileMenu.tsx
  src/widgets/sidebar/sidebar.tsx
Labels: bug

#98 Refactor/proj 234
  package.json
  pnpm-lock.yaml
  src/features/posts/ui/imagePostModal/imagePostModal.tsx
  src/features/posts/ui/post/postForm/usePostForm.ts
  src/widgets/carousel/carousel.module.scss
  src/widgets/carousel/carousel.tsx
  src/widgets/carousel/carouselItem/carouselItem.module.scss
  src/widgets/carousel/carouselItem/carouselItem.tsx
  src/widgets/carousel/carouselItem/index.ts
  src/widgets/carousel/imageRenderer/imageRenderer.tsx
  src/widgets/carousel/imageRenderer/index.ts
Labels: refactor

#97 refactoring PublicPosts
  src/features/posts/ui/imagePostModal/imagePostModal.tsx
  src/features/posts/ui/post/postForm/usePostForm.ts
  src/features/posts/ui/postList/postList.tsx
  src/features/profile/ui/profile/profile.tsx
  src/features/public/ui/publicPost/publicPost.module.scss
  src/features/public/ui/publicPost/publicPost.tsx
  src/shared/ui/profileAvatar/profileAvatar.tsx
Labels: refactor
