Repository NoName-ForTeam/photo-fiesta, pull requests merged in 2025-03, with the labels that each got.

#104 feature/PROJ-212: add OAuth GitHub authorization
  src/features/auth/ui/authCard/authCard.tsx
  src/pages/auth/auth-callback/github/index.tsx
  src/shared/config/apiURLs.ts
Labels: feature

#106 feature/PROJ-212.1 fix: ESLint errors
  src/pages/auth/auth-callback/github/index.tsx
Labels: bug, feature

#107 PROJ-246 refactor: fix InfiniteScroll on mobile 360*640
  src/features/posts/ui/postList/postList.module.scss
  src/features/posts/ui/postList/postList.tsx
Labels: refactor
